#!/usr/bin/env sh

seted() {
  while [ $# != 0 ]; do
    if command -v "$1" >/dev/null 2>/dev/null; then
      EDITOR="$1"
      return
    fi

    shift
  done

  return 1
}

seted "nvim" "vim" "vi" "nano" || {
  printf >&2 "No suitable text editor found!\n"
  exit 1
}

if [ ! -t 2 ] || [ ! -t 1 ]; then
  exec "${TERMINAL:-xterm}" -e "$EDITOR" "$@"
else
  exec "$EDITOR" "$@"
fi
