.PHONY: output install run

output:
	cargo build --bin bkmk --release

install:
	@echo INCOMPLETE

run:
	@echo 'The "run" action is disabled here, since multiple binaries are being made.'
	@echo 'I might find another solution later.'
